export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const USER_LOGOUT = 'USER_LOGOUT';
export const SEND_USER_AUTHENTICATION = 'SEND_USER_AUTHENTICATION';
export const SEND_USER_AUTHENTICATION_ATTEMPT = 'SEND_USER_AUTHENTICATION_ATTEMPT';
export const SEND_USER_AUTHENTICATION_SUCCESS = 'SEND_USER_AUTHENTICATION_SUCCESS';
export const SEND_USER_AUTHENTICATION_FAIL= 'SEND_USER_AUTHENTICATION_FAIL';